import { supabase } from '../lib/supabase';
type QueryResult = { data: unknown; error: Error | null };
type Query = PromiseLike<QueryResult> & { select(value: string): Query; order(column: string, options: { ascending: boolean }): Query; eq(column: string, value: string): Query; neq(column: string, value: string): Query };
type DatabaseClient = { from(table: string): Query; rpc(name: string, args?: Record<string, unknown>): Promise<QueryResult> };
const db = supabase as unknown as DatabaseClient;
export type WorkMode='design_only'|'design_production'|'setup_only'; export type TaskType='daily'|'activity'; export type DesignType='banner'|'standee'|'poster'|'special'; export type StageType='design'|'production'|'setup'; export type StageStatus='unclaimed'|'scheduled'|'arranged'|'in_progress'|'awaiting_agent_confirmation'|'revision'|'completed'|'cancelled';
export type DisplayEmployee={full_name:string|null;nickname:string|null};
export type DesignerStage={id:string;stage_type:StageType;status:StageStatus;assignee_profile_id:string|null;assignee_employee_id:string|null;assignee:DisplayEmployee|null;accepted_at:string|null;submitted_at:string|null;confirmed_at:string|null;feedback:string|null;feedback_count:number};
export type DesignerRequestV2={id:string;creator_profile_id:string|null;request_type:DesignType;task_type:TaskType|null;other_design_type:string|null;work_mode:WorkMode|null;status:string;creator_name:string|null;platform_user_id:string|null;platform_account:string|null;event_start_at:string|null;event_end_at:string|null;design_content:string|null;special_content:string|null;style:string|null;color:string|null;specification:string|null;live_room:string|null;reference_material_status:'not_required'|'provided';reference_urls:string[];design_urls:string[];created_at:string;applicant:DisplayEmployee|null;creator:{manager:DisplayEmployee|null}|null;region:{name:string|null}|null;stages:DesignerStage[]};
export type DesignerRequestCreator={id:string;creator_entity_id:string|null;region_id:string|null;region_name:string|null;platform:string;platform_user_id:string;platform_account:string;creator_name:string;creator_type:string;manager_employee_id:string|null;manager_name:string|null};
export type CreateDesignerRequest={creatorProfileId:string;workMode:WorkMode;taskType:TaskType;requestType:DesignType;otherDesignType:string;eventStartAt:string;eventEndAt:string;content:string;style:string;color:string;specification:string;specialContent:string;referenceMaterialStatus:'not_required'|'provided';liveRoom:string};
const select='id,creator_profile_id,request_type,task_type,other_design_type,work_mode,status,creator_name,platform_user_id,platform_account,event_start_at,event_end_at,design_content,special_content,style,color,specification,live_room,reference_material_status,reference_urls,design_urls,created_at,applicant:employees!designer_requests_agent_employee_id_fkey(full_name,nickname),creator:creator_profiles!designer_requests_creator_profile_id_fkey(manager:employees!creator_profiles_manager_employee_id_fkey(full_name,nickname)),region:regions!designer_requests_region_id_fkey(name),stages:designer_request_stages(id,stage_type,status,assignee_profile_id,assignee_employee_id,accepted_at,submitted_at,confirmed_at,feedback,feedback_count,assignee:employees!designer_request_stages_assignee_employee_id_fkey(full_name,nickname))';
type StageRow = DesignerStage & { request: DesignerRequestV2 };
const map = (row: DesignerRequestV2): DesignerRequestV2 => ({ ...row, reference_urls: row.reference_urls ?? [], design_urls: row.design_urls ?? [], stages: row.stages ?? [] });
export const designerRequestService={
 async listAgentRequests(){const {data,error}=await db.from('designer_requests').select(select).order('created_at',{ascending:false});if(error)throw error;return((data as DesignerRequestV2[]|null)??[]).map(map)},
 async listEligibleCreators(){const {data,error}=await db.rpc('list_designer_request_creators');if(error)throw error;return((data as DesignerRequestCreator[]|null)??[])},
 async listAvailableStages(){const {data,error}=await db.from('designer_request_stages').select(`id,stage_type,status,assignee_profile_id,assignee_employee_id,accepted_at,submitted_at,confirmed_at,feedback,feedback_count,request:designer_requests!inner(${select})`).eq('status','unclaimed');if(error)throw error;return((data as StageRow[]|null)??[]).map((row)=>({...map(row.request),stage:row}))},
 async listMyStages(id:string){const {data,error}=await db.from('designer_request_stages').select(`id,stage_type,status,assignee_profile_id,assignee_employee_id,accepted_at,submitted_at,confirmed_at,feedback,feedback_count,request:designer_requests!inner(${select})`).eq('assignee_profile_id',id).neq('status','completed');if(error)throw error;return((data as StageRow[]|null)??[]).map((row)=>({...map(row.request),stage:row}))},
 async create(x:CreateDesignerRequest){const {data,error}=await db.rpc('create_designer_request',{p_creator_profile_id:x.creatorProfileId,p_work_mode:x.workMode,p_request_type:x.requestType,p_task_type:x.taskType,p_other_design_type:x.requestType==='special'?x.otherDesignType.trim():null,p_event_start_at:x.eventStartAt||null,p_event_end_at:x.eventEndAt||null,p_design_content:x.content||null,p_style:x.style||null,p_color:x.color||null,p_specification:x.specification||null,p_special_content:x.specialContent||null,p_reference_material_status:x.referenceMaterialStatus,p_live_room:x.liveRoom||null});if(error)throw error;return data as string},
 async update(id:string,x:CreateDesignerRequest){const {error}=await db.rpc('update_designer_request',{p_request_id:id,p_task_type:x.taskType,p_request_type:x.requestType,p_other_design_type:x.requestType==='special'?x.otherDesignType.trim():null,p_event_start_at:x.eventStartAt||null,p_event_end_at:x.eventEndAt||null,p_design_content:x.content||null,p_special_content:x.specialContent||null,p_style:x.style||null,p_color:x.color||null,p_specification:x.specification||null,p_live_room:x.liveRoom||null,p_reference_material_status:x.referenceMaterialStatus});if(error)throw error},
 async cancel(id:string){const {error}=await db.rpc('cancel_designer_request',{p_request_id:id});if(error)throw error},
 async claim(id:string){const {error}=await db.rpc('claim_designer_request_stage',{p_stage_id:id});if(error)throw error}, async advance(id:string,a:'arrange'|'start'){const {error}=await db.rpc('advance_designer_request_stage',{p_stage_id:id,p_action:a});if(error)throw error}, async submit(id:string){const {error}=await db.rpc('submit_designer_request_stage',{p_stage_id:id});if(error)throw error}, async confirm(id:string){const {error}=await db.rpc('confirm_designer_request_stage',{p_stage_id:id});if(error)throw error}, async returnStage(id:string,note:string){const {error}=await db.rpc('return_designer_request_stage',{p_stage_id:id,p_feedback:note});if(error)throw error}
};
export const formatCreatorLabel=(c:Pick<DesignerRequestCreator,'creator_name'|'platform'|'platform_user_id'>)=>`${c.creator_name} · ${c.platform==='tiktok'?'TikTok':'抖音'} ${c.platform_user_id}`;
