begin;

create or replace function public.submit_creator_cumulative_revenue(
  p_creator_profile_id uuid, p_cumulative_amount numeric, p_data_date date, p_idempotency_key uuid, p_note text default null, p_source text default 'manual')
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare c public.creator_profiles; s public.creator_revenue_cumulative_state; ps public.creator_revenue_cumulative_period_state; e public.creator_revenue_cumulative_records; raw public.creator_revenue_cumulative_records; w public.creator_weekly_revenue_records; v_start date; v_end date; v_amount numeric; v_count integer; v_employee uuid:=public.current_user_employee_id();
begin
  if p_cumulative_amount is null or p_cumulative_amount<0 then raise exception 'Cumulative amount must be a non-negative number.'; end if;
  if p_data_date is null or p_idempotency_key is null then raise exception 'Data date and idempotency key are required.'; end if;
  if p_source<>'manual' then raise exception 'Only manual cumulative submissions are allowed by this RPC.'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_creator_profile_id::text,0));
  select * into c from public.apply_due_creator_revenue_input_mode(p_creator_profile_id,p_data_date); perform public.assert_creator_cumulative_revenue_access(c);
  if c.revenue_cycle<>'weekly' or c.revenue_input_mode<>'cumulative' then raise exception 'Cumulative calculation is only available for weekly cumulative creator profiles.'; end if;
  select * into e from public.creator_revenue_cumulative_records where creator_profile_id=c.id and idempotency_key=p_idempotency_key;
  if e.id is not null then select * into w from public.creator_weekly_revenue_records where id=e.related_weekly_revenue_record_id; return jsonb_build_object('idempotent',true,'entry_kind',e.entry_kind,'weekly_record',to_jsonb(w),'previous_cumulative_amount',e.previous_cumulative_amount,'calculated_period_amount',e.calculated_period_amount); end if;
  select * into s from public.creator_revenue_cumulative_state where creator_profile_id=c.id for update; if s.creator_profile_id is null then insert into public.creator_revenue_cumulative_state(creator_profile_id) values(c.id) returning * into s; end if;
  v_start:=public.creator_weekly_revenue_period_start(p_data_date); v_end:=public.creator_weekly_revenue_period_end(v_start);
  if not s.chain_active then insert into public.creator_revenue_cumulative_records(creator_profile_id,creator_entity_id,platform,platform_uid,cumulative_amount,data_date,week_start_date,entered_by_employee_id,source,entry_kind,idempotency_key,note) values(c.id,c.creator_entity_id,c.platform,c.platform_user_id,p_cumulative_amount,p_data_date,v_start,v_employee,p_source,'baseline',p_idempotency_key,nullif(btrim(coalesce(p_note,'')),'')) returning * into raw; update public.creator_revenue_cumulative_state set latest_cumulative_amount=p_cumulative_amount,latest_raw_record_id=raw.id,chain_active=true,chain_generation=chain_generation+1,updated_at=now() where creator_profile_id=c.id; return jsonb_build_object('idempotent',false,'entry_kind','baseline','weekly_record',null,'previous_cumulative_amount',null,'calculated_period_amount',null); end if;
  if s.calculation_resumes_week_start_date is not null and v_start<s.calculation_resumes_week_start_date then raise exception 'The new cumulative baseline starts calculating from the next period.'; end if;
  if p_data_date<(select data_date from public.creator_revenue_cumulative_records where id=s.latest_raw_record_id) then raise exception 'Data date cannot be earlier than the latest cumulative observation.'; end if;
  if p_cumulative_amount<s.latest_cumulative_amount then raise exception 'Cumulative amount cannot be lower than the previous cumulative amount. Ask a Super Admin to reset the baseline.'; end if;
  select * into ps from public.creator_revenue_cumulative_period_state where creator_profile_id=c.id and week_start_date=v_start and chain_generation=s.chain_generation and is_active for update;
  if ps.creator_profile_id is null then insert into public.creator_revenue_cumulative_period_state(creator_profile_id,week_start_date,chain_generation,opening_cumulative_amount,opening_raw_record_id) values(c.id,v_start,s.chain_generation,s.latest_cumulative_amount,s.latest_raw_record_id) returning * into ps; end if;
  v_amount:=p_cumulative_amount-ps.opening_cumulative_amount;
  if ps.weekly_revenue_record_id is not null then select * into w from public.creator_weekly_revenue_records q where q.id=ps.weekly_revenue_record_id and q.creator_profile_id=c.id and q.week_start_date=v_start and public.creator_weekly_revenue_is_cumulative(q) for update; if w.id is null then raise exception 'Cumulative weekly revenue ownership reference is invalid.'; end if; update public.creator_weekly_revenue_records set revenue_amount=v_amount,agent_note=nullif(btrim(coalesce(p_note,'')),''),status='submitted' where id=w.id returning * into w;
  else select count(*) into v_count from public.creator_weekly_revenue_records where creator_profile_id=c.id and week_start_date=v_start; if v_count>0 then raise exception 'A weekly revenue record already exists for this period and cannot be overwritten by cumulative mode.'; end if; insert into public.creator_weekly_revenue_records(creator_profile_id,week_start_date,week_end_date,revenue_amount,agent_note,status,source,is_cumulative_generated,revenue_entry_kind) values(c.id,v_start,v_end,v_amount,nullif(btrim(coalesce(p_note,'')),''),'submitted','manual',true,'cumulative_generated') returning * into w; update public.creator_revenue_cumulative_period_state set weekly_revenue_record_id=w.id,updated_at=now() where creator_profile_id=c.id and week_start_date=v_start and chain_generation=s.chain_generation; end if;
  insert into public.creator_revenue_cumulative_records(creator_profile_id,creator_entity_id,platform,platform_uid,cumulative_amount,previous_cumulative_amount,calculated_period_amount,data_date,week_start_date,entered_by_employee_id,source,entry_kind,related_weekly_revenue_record_id,idempotency_key,note) values(c.id,c.creator_entity_id,c.platform,c.platform_user_id,p_cumulative_amount,s.latest_cumulative_amount,v_amount,p_data_date,v_start,v_employee,p_source,'calculation',w.id,p_idempotency_key,nullif(btrim(coalesce(p_note,'')),'')) returning * into raw;
  update public.creator_revenue_cumulative_state set latest_cumulative_amount=p_cumulative_amount,latest_raw_record_id=raw.id,calculation_resumes_week_start_date=null,updated_at=now() where creator_profile_id=c.id;
  return jsonb_build_object('idempotent',false,'entry_kind','calculation','weekly_record',to_jsonb(w),'previous_cumulative_amount',s.latest_cumulative_amount,'calculated_period_amount',v_amount);
end; $$;

create or replace function public.submit_creator_cumulative_revenue_with_backfills(p_creator_profile_id uuid,p_cumulative_amount numeric,p_data_date date,p_idempotency_key uuid,p_backfills jsonb,p_note text default null)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare c public.creator_profiles; s public.creator_revenue_cumulative_state; e public.creator_revenue_cumulative_records; raw public.creator_revenue_cumulative_records; ps public.creator_revenue_cumulative_period_state; w public.creator_weekly_revenue_records; x record; v_start date; v_end date; v_prev_start date; v_cursor date; v_expected jsonb:='[]'::jsonb; v_actual jsonb:=coalesce(p_backfills,'[]'::jsonb); v_sum numeric:=0; v_generated numeric; v_employee uuid:=public.current_user_employee_id();
begin
 if p_cumulative_amount is null or p_cumulative_amount<0 or p_data_date is null or p_idempotency_key is null or jsonb_typeof(v_actual)<>'array' then raise exception 'Cumulative amount, data date, idempotency key, and a backfill array are required.'; end if;
 perform pg_advisory_xact_lock(hashtextextended(p_creator_profile_id::text,0)); select * into c from public.apply_due_creator_revenue_input_mode(p_creator_profile_id,p_data_date); perform public.assert_creator_cumulative_revenue_access(c); if c.revenue_cycle<>'weekly' or c.revenue_input_mode<>'cumulative' then raise exception 'Cumulative calculation is only available for weekly cumulative creator profiles.'; end if;
 select * into e from public.creator_revenue_cumulative_records where creator_profile_id=c.id and idempotency_key=p_idempotency_key; if e.id is not null then select * into w from public.creator_weekly_revenue_records where id=e.related_weekly_revenue_record_id; return jsonb_build_object('idempotent',true,'entry_kind',e.entry_kind,'weekly_record',to_jsonb(w)); end if;
 select * into s from public.creator_revenue_cumulative_state where creator_profile_id=c.id for update; if s.creator_profile_id is null or not s.chain_active then raise exception 'Establish a cumulative baseline before using backfill.'; end if;
 if p_data_date<(select data_date from public.creator_revenue_cumulative_records where id=s.latest_raw_record_id) then raise exception 'Data date cannot be earlier than the latest cumulative observation.'; end if; if p_cumulative_amount<s.latest_cumulative_amount then raise exception 'Cumulative amount cannot be lower than the previous cumulative amount.'; end if;
 v_start:=public.creator_weekly_revenue_period_start(p_data_date); select week_start_date into v_prev_start from public.creator_revenue_cumulative_records where id=s.latest_raw_record_id; v_cursor:=public.creator_weekly_revenue_period_start(public.creator_weekly_revenue_period_end(v_prev_start)+1);
 while v_cursor<v_start loop v_expected:=v_expected || jsonb_build_array(to_jsonb(v_cursor)); v_cursor:=public.creator_weekly_revenue_period_start(public.creator_weekly_revenue_period_end(v_cursor)+1); end loop;
 if jsonb_array_length(v_expected)=0 then raise exception 'There are no missing periods for a backfill submission.'; end if;
 if (select count(*) from jsonb_array_elements(v_actual) b where not (b ? 'period_start' and b ? 'weekly_amount') or (b->>'period_start')::date <> public.creator_weekly_revenue_period_start((b->>'period_start')::date) or (b->>'weekly_amount')::numeric<0) <> jsonb_array_length(v_actual) then raise exception 'Each backfill requires a canonical period start and a non-negative weekly amount.'; end if;
 if (select count(distinct (b->>'period_start')::date) from jsonb_array_elements(v_actual) b) <> jsonb_array_length(v_actual) or (select jsonb_agg(to_jsonb((b->>'period_start')::date) order by (b->>'period_start')::date) from jsonb_array_elements(v_actual) b) is distinct from v_expected then raise exception 'Backfills must match every missing canonical period exactly once.'; end if;
 select coalesce(sum((b->>'weekly_amount')::numeric),0) into v_sum from jsonb_array_elements(v_actual) b; v_generated:=p_cumulative_amount-s.latest_cumulative_amount-v_sum; if v_generated<0 then raise exception 'Manual backfill total cannot exceed cumulative growth.'; end if;
 if exists(select 1 from jsonb_array_elements(v_actual) b join public.creator_weekly_revenue_records q on q.creator_profile_id=c.id and q.week_start_date=(b->>'period_start')::date) then raise exception 'A missing period already has weekly revenue and cannot be backfilled.'; end if;
 if exists(select 1 from public.creator_weekly_revenue_records q where q.creator_profile_id=c.id and q.week_start_date=v_start) then raise exception 'A weekly revenue record already exists for the current period.'; end if;
 for x in select (b->>'period_start')::date as start_date,(b->>'weekly_amount')::numeric as amount from jsonb_array_elements(v_actual) b loop insert into public.creator_weekly_revenue_records(creator_profile_id,week_start_date,week_end_date,revenue_amount,agent_note,status,source,is_cumulative_generated,revenue_entry_kind) values(c.id,x.start_date,public.creator_weekly_revenue_period_end(x.start_date),x.amount,nullif(btrim(coalesce(p_note,'')),''),'submitted','manual',false,'cumulative_manual_backfill'); end loop;
 insert into public.creator_revenue_cumulative_period_state(creator_profile_id,week_start_date,chain_generation,opening_cumulative_amount,opening_raw_record_id) values(c.id,v_start,s.chain_generation,s.latest_cumulative_amount,s.latest_raw_record_id) returning * into ps;
 insert into public.creator_weekly_revenue_records(creator_profile_id,week_start_date,week_end_date,revenue_amount,agent_note,status,source,is_cumulative_generated,revenue_entry_kind) values(c.id,v_start,public.creator_weekly_revenue_period_end(v_start),v_generated,nullif(btrim(coalesce(p_note,'')),''),'submitted','manual',true,'cumulative_generated') returning * into w;
 update public.creator_revenue_cumulative_period_state set weekly_revenue_record_id=w.id,updated_at=now() where creator_profile_id=c.id and week_start_date=v_start and chain_generation=s.chain_generation;
 insert into public.creator_revenue_cumulative_records(creator_profile_id,creator_entity_id,platform,platform_uid,cumulative_amount,previous_cumulative_amount,calculated_period_amount,data_date,week_start_date,entered_by_employee_id,source,entry_kind,related_weekly_revenue_record_id,idempotency_key,note) values(c.id,c.creator_entity_id,c.platform,c.platform_user_id,p_cumulative_amount,s.latest_cumulative_amount,v_generated,p_data_date,v_start,v_employee,'manual','calculation',w.id,p_idempotency_key,nullif(btrim(coalesce(p_note,'')),'')) returning * into raw;
 update public.creator_revenue_cumulative_state set latest_cumulative_amount=p_cumulative_amount,latest_raw_record_id=raw.id,calculation_resumes_week_start_date=null,updated_at=now() where creator_profile_id=c.id;
 return jsonb_build_object('idempotent',false,'entry_kind','calculation','weekly_record',to_jsonb(w),'previous_cumulative_amount',s.latest_cumulative_amount,'calculated_period_amount',v_generated,'backfill_count',jsonb_array_length(v_actual));
end; $$;

create or replace function public.save_direct_creator_weekly_revenue(p_creator_profile_id uuid,p_data_date date,p_revenue_amount numeric,p_agent_note text,p_idempotency_key uuid)
returns public.creator_weekly_revenue_records language plpgsql security definer set search_path=public,pg_temp as $$
declare c public.creator_profiles; r public.creator_weekly_revenue_direct_save_requests; w public.creator_weekly_revenue_records; v_start date; v_end date;
begin
 if auth.uid() is null or p_creator_profile_id is null or p_data_date is null or p_idempotency_key is null or p_revenue_amount is null or p_revenue_amount<0 then raise exception 'Valid creator, date, idempotency key, and non-negative revenue are required.'; end if;
 perform pg_advisory_xact_lock(hashtextextended(p_creator_profile_id::text,0)); select * into c from public.apply_due_creator_revenue_input_mode(p_creator_profile_id,p_data_date);
 if c.id is null or c.status<>'active' or c.membership_status<>'active' or c.revenue_cycle<>'weekly' or c.revenue_input_mode<>'direct' then raise exception 'Direct weekly revenue is only available for active weekly direct creator profiles.'; end if;
 if not exists(select 1 from public.creator_entities e where e.id=c.creator_entity_id and e.status='active') then raise exception 'Creator entity is not active for current revenue actions.'; end if;
 if not public.current_user_has_permission('agent-revenue-data','use') or c.manager_employee_id is distinct from public.current_user_employee_id() or not public.current_user_can_access_region(c.region_id) then raise exception 'No permission to save direct weekly revenue for this creator.'; end if;
 select * into r from public.creator_weekly_revenue_direct_save_requests where creator_profile_id=c.id and idempotency_key=p_idempotency_key; if r.id is not null then select * into w from public.creator_weekly_revenue_records where id=r.weekly_revenue_record_id; return w; end if;
 v_start:=public.creator_weekly_revenue_period_start(p_data_date); v_end:=public.creator_weekly_revenue_period_end(v_start); select * into w from public.creator_weekly_revenue_records where creator_profile_id=c.id and week_start_date=v_start for update;
 if w.id is not null and public.creator_weekly_revenue_is_cumulative(w) then raise exception 'This period already has cumulative revenue and cannot be overwritten by direct input.'; end if;
 if w.id is null then insert into public.creator_weekly_revenue_records(creator_profile_id,week_start_date,week_end_date,revenue_amount,agent_note,status,source,is_cumulative_generated,revenue_entry_kind) values(c.id,v_start,v_end,p_revenue_amount,nullif(btrim(coalesce(p_agent_note,'')),''),'submitted','manual',false,'direct') returning * into w; else update public.creator_weekly_revenue_records set revenue_amount=p_revenue_amount,agent_note=nullif(btrim(coalesce(p_agent_note,'')),''),status='submitted' where id=w.id returning * into w; end if;
 insert into public.creator_weekly_revenue_direct_save_requests(creator_profile_id,requested_by_profile_id,idempotency_key,weekly_revenue_record_id) values(c.id,auth.uid(),p_idempotency_key,w.id); return w;
end; $$;

commit;
