begin;

-- Phase 2 keeps the platform total as immutable raw observations.  The weekly
-- table remains the single source used by existing Management Revenue/ranking.
-- `source` describes collection channel; this marker separately identifies
-- records generated by the cumulative calculation engine.
alter table public.creator_weekly_revenue_records
  add column if not exists is_cumulative_generated boolean not null default false;

create table public.creator_revenue_cumulative_records (
  id uuid primary key default gen_random_uuid(),
  creator_profile_id uuid not null references public.creator_profiles(id) on delete restrict,
  creator_entity_id uuid,
  platform public.creator_platform not null,
  platform_uid text not null,
  cumulative_amount numeric(14,2) not null check (cumulative_amount >= 0),
  previous_cumulative_amount numeric(14,2),
  calculated_period_amount numeric(14,2),
  data_date date not null,
  week_start_date date not null,
  entered_at timestamptz not null default now(),
  entered_by_employee_id uuid references public.employees(id) on delete set null,
  source text not null default 'manual' check (source in ('manual', 'import', 'api')),
  entry_kind text not null check (entry_kind in ('baseline', 'calculation', 'reset')),
  related_weekly_revenue_record_id uuid references public.creator_weekly_revenue_records(id) on delete set null,
  idempotency_key uuid not null,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint creator_revenue_cumulative_records_profile_idempotency_key unique (creator_profile_id, idempotency_key)
);

create index creator_revenue_cumulative_records_profile_entered_idx
  on public.creator_revenue_cumulative_records(creator_profile_id, entered_at desc);

create table public.creator_revenue_cumulative_state (
  creator_profile_id uuid primary key references public.creator_profiles(id) on delete restrict,
  latest_cumulative_amount numeric(14,2),
  latest_raw_record_id uuid,
  chain_active boolean not null default false,
  chain_generation integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.creator_revenue_cumulative_state
  add constraint creator_revenue_cumulative_state_latest_raw_fkey
  foreign key (latest_raw_record_id) references public.creator_revenue_cumulative_records(id) on delete set null;

create table public.creator_revenue_cumulative_period_state (
  creator_profile_id uuid not null references public.creator_profiles(id) on delete restrict,
  week_start_date date not null,
  chain_generation integer not null,
  opening_cumulative_amount numeric(14,2) not null,
  opening_raw_record_id uuid references public.creator_revenue_cumulative_records(id) on delete restrict,
  weekly_revenue_record_id uuid references public.creator_weekly_revenue_records(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (creator_profile_id, week_start_date, chain_generation)
);

create unique index creator_revenue_cumulative_period_state_weekly_record_unique
  on public.creator_revenue_cumulative_period_state(weekly_revenue_record_id)
  where weekly_revenue_record_id is not null;

create index creator_revenue_cumulative_period_state_active_idx
  on public.creator_revenue_cumulative_period_state(creator_profile_id, week_start_date)
  where is_active;

-- Raw observations are append-only.  All writes happen through SECURITY DEFINER
-- RPCs below; there is deliberately no client INSERT/UPDATE/DELETE permission.
create or replace function public.prevent_creator_revenue_cumulative_records_changes()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  raise exception 'Creator cumulative revenue records are append-only.';
end;
$$;

create trigger prevent_creator_revenue_cumulative_records_changes
before update or delete on public.creator_revenue_cumulative_records
for each row execute function public.prevent_creator_revenue_cumulative_records_changes();

alter table public.creator_revenue_cumulative_records enable row level security;
alter table public.creator_revenue_cumulative_state enable row level security;
alter table public.creator_revenue_cumulative_period_state enable row level security;
revoke all on public.creator_revenue_cumulative_records, public.creator_revenue_cumulative_state, public.creator_revenue_cumulative_period_state from public, anon, authenticated;

-- Switching away from cumulative invalidates the global chain.  Re-entering
-- cumulative must therefore establish a fresh baseline through the RPC.
create or replace function public.invalidate_creator_cumulative_chain_on_mode_change()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if old.revenue_input_mode = 'cumulative' and new.revenue_input_mode <> 'cumulative' then
    update public.creator_revenue_cumulative_state
    set chain_active = false, updated_at = now()
    where creator_profile_id = new.id;
  end if;
  return new;
end;
$$;

create trigger invalidate_creator_cumulative_chain_on_mode_change
after update of revenue_input_mode on public.creator_profiles
for each row execute function public.invalidate_creator_cumulative_chain_on_mode_change();

create or replace function public.assert_creator_cumulative_revenue_access(
  p_creator_profile public.creator_profiles,
  p_allow_super_admin boolean default true
)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare v_employee_id uuid := public.current_user_employee_id();
begin
  if auth.uid() is null then raise exception 'Authentication is required.'; end if;
  if p_creator_profile.id is null or p_creator_profile.status <> 'active' or p_creator_profile.membership_status <> 'active' then
    raise exception 'Active creator profile not found.';
  end if;
  if p_allow_super_admin and public.current_user_is_super_admin() then return; end if;
  if public.current_user_has_permission('agent-revenue-data', 'use')
     and p_creator_profile.manager_employee_id = v_employee_id then return; end if;
  if public.current_user_has_permission('management-revenue-data', 'use')
     and public.current_user_can_access_region(p_creator_profile.region_id) then return; end if;
  raise exception 'No permission to manage this creator cumulative revenue.';
end;
$$;

create or replace function public.get_creator_cumulative_revenue_context(p_creator_profile_id uuid, p_data_date date)
returns table (
  latest_cumulative_amount numeric,
  chain_active boolean,
  latest_data_date date,
  current_week_start_date date,
  opening_cumulative_amount numeric,
  estimated_period_amount numeric
)
language plpgsql security definer set search_path = public, pg_temp as $$
declare c public.creator_profiles; s public.creator_revenue_cumulative_state; p public.creator_revenue_cumulative_period_state;
begin
  if p_data_date is null then raise exception 'Data date is required.'; end if;
  select * into c from public.creator_profiles where id = p_creator_profile_id;
  perform public.assert_creator_cumulative_revenue_access(c);
  select * into s from public.creator_revenue_cumulative_state where creator_profile_id = c.id;
  select * into p from public.creator_revenue_cumulative_period_state
  where creator_profile_id = c.id and week_start_date = public.creator_weekly_revenue_period_start(p_data_date)
    and chain_generation = coalesce(s.chain_generation, 0) and is_active;
  return query select s.latest_cumulative_amount, coalesce(s.chain_active, false),
    (select r.data_date from public.creator_revenue_cumulative_records r where r.id = s.latest_raw_record_id),
    public.creator_weekly_revenue_period_start(p_data_date),
    p.opening_cumulative_amount,
    case when p.opening_cumulative_amount is null or s.latest_cumulative_amount is null then null else s.latest_cumulative_amount - p.opening_cumulative_amount end;
end;
$$;

create or replace function public.submit_creator_cumulative_revenue(
  p_creator_profile_id uuid,
  p_cumulative_amount numeric,
  p_data_date date,
  p_idempotency_key uuid,
  p_note text default null,
  p_source text default 'manual'
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare
  c public.creator_profiles; s public.creator_revenue_cumulative_state; period_state public.creator_revenue_cumulative_period_state;
  v_employee_id uuid := public.current_user_employee_id(); v_week_start date; v_week_end date;
  v_existing_raw public.creator_revenue_cumulative_records; v_raw public.creator_revenue_cumulative_records;
  v_weekly public.creator_weekly_revenue_records; v_weekly_count integer; v_period_amount numeric;
begin
  if p_cumulative_amount is null or p_cumulative_amount < 0 then raise exception 'Cumulative amount must be a non-negative number.'; end if;
  if p_data_date is null or p_idempotency_key is null then raise exception 'Data date and idempotency key are required.'; end if;
  -- This authenticated RPC is the Phase 2 manual entry point. Future imports
  -- must use a separately controlled server-side entry point, not a client-
  -- supplied audit source.
  if p_source <> 'manual' then raise exception 'Only manual cumulative submissions are allowed by this RPC.'; end if;
  select * into c from public.creator_profiles where id = p_creator_profile_id;
  perform public.assert_creator_cumulative_revenue_access(c);
  if c.revenue_cycle <> 'weekly' or c.revenue_input_mode <> 'cumulative' then
    raise exception 'Cumulative calculation is only available for weekly cumulative creator profiles.';
  end if;
  -- Serialize all cumulative calls for a Profile, including first use where no state row exists.
  perform pg_advisory_xact_lock(hashtextextended(p_creator_profile_id::text, 0));
  select * into v_existing_raw from public.creator_revenue_cumulative_records
  where creator_profile_id = p_creator_profile_id and idempotency_key = p_idempotency_key;
  if v_existing_raw.id is not null then
    select * into v_weekly from public.creator_weekly_revenue_records where id = v_existing_raw.related_weekly_revenue_record_id;
    return jsonb_build_object('idempotent', true, 'entry_kind', v_existing_raw.entry_kind, 'weekly_record', to_jsonb(v_weekly), 'previous_cumulative_amount', v_existing_raw.previous_cumulative_amount, 'calculated_period_amount', v_existing_raw.calculated_period_amount);
  end if;
  select * into s from public.creator_revenue_cumulative_state where creator_profile_id = p_creator_profile_id for update;
  if s.creator_profile_id is null then
    insert into public.creator_revenue_cumulative_state(creator_profile_id) values (p_creator_profile_id) returning * into s;
  end if;
  v_week_start := public.creator_weekly_revenue_period_start(p_data_date);
  v_week_end := public.creator_weekly_revenue_period_end(v_week_start);
  if not s.chain_active then
    insert into public.creator_revenue_cumulative_records(creator_profile_id, creator_entity_id, platform, platform_uid, cumulative_amount, data_date, week_start_date, entered_by_employee_id, source, entry_kind, idempotency_key, note)
    values(c.id, c.creator_entity_id, c.platform, c.platform_user_id, p_cumulative_amount, p_data_date, v_week_start, v_employee_id, p_source, 'baseline', p_idempotency_key, nullif(btrim(coalesce(p_note,'')),'')) returning * into v_raw;
    update public.creator_revenue_cumulative_state set latest_cumulative_amount = p_cumulative_amount, latest_raw_record_id = v_raw.id, chain_active = true, chain_generation = chain_generation + 1, updated_at = now() where creator_profile_id = c.id returning * into s;
    return jsonb_build_object('idempotent', false, 'entry_kind', 'baseline', 'weekly_record', null, 'previous_cumulative_amount', null, 'calculated_period_amount', null);
  end if;
  if p_data_date < (select r.data_date from public.creator_revenue_cumulative_records r where r.id = s.latest_raw_record_id) then
    raise exception 'Data date cannot be earlier than the latest cumulative observation.';
  end if;
  if p_cumulative_amount < s.latest_cumulative_amount then raise exception 'Cumulative amount cannot be lower than the previous cumulative amount. Ask a Super Admin to reset the baseline.'; end if;
  select * into period_state from public.creator_revenue_cumulative_period_state
  where creator_profile_id = c.id and week_start_date = v_week_start and chain_generation = s.chain_generation and is_active for update;
  if period_state.creator_profile_id is null then
    insert into public.creator_revenue_cumulative_period_state(creator_profile_id, week_start_date, chain_generation, opening_cumulative_amount, opening_raw_record_id)
    values(c.id, v_week_start, s.chain_generation, s.latest_cumulative_amount, s.latest_raw_record_id) returning * into period_state;
  end if;
  v_period_amount := p_cumulative_amount - period_state.opening_cumulative_amount;
  if period_state.weekly_revenue_record_id is not null then
    select * into v_weekly from public.creator_weekly_revenue_records
    where id = period_state.weekly_revenue_record_id and creator_profile_id = c.id and week_start_date = v_week_start
      and is_cumulative_generated = true for update;
    if v_weekly.id is null then raise exception 'Cumulative weekly revenue ownership reference is invalid. Ask an administrator to resolve it.'; end if;
    update public.creator_weekly_revenue_records set revenue_amount = v_period_amount, agent_note = nullif(btrim(coalesce(p_note,'')),''), status = 'submitted' where id = v_weekly.id returning * into v_weekly;
  else
    select count(*) into v_weekly_count from public.creator_weekly_revenue_records where creator_profile_id = c.id and week_start_date = v_week_start;
    if v_weekly_count > 1 then raise exception 'Multiple weekly revenue records already exist for this creator and period. Ask an administrator to resolve the historical duplicate.'; end if;
    if v_weekly_count = 1 then raise exception 'A direct weekly revenue record already exists for this period and cannot be overwritten by cumulative mode.'; end if;
    insert into public.creator_weekly_revenue_records(creator_profile_id, week_start_date, week_end_date, revenue_amount, agent_note, status, source, is_cumulative_generated)
    values(c.id, v_week_start, v_week_end, v_period_amount, nullif(btrim(coalesce(p_note,'')),''), 'submitted', 'manual', true)
    returning * into v_weekly;
    update public.creator_revenue_cumulative_period_state
    set weekly_revenue_record_id = v_weekly.id, updated_at = now()
    where creator_profile_id = period_state.creator_profile_id
      and week_start_date = period_state.week_start_date
      and chain_generation = period_state.chain_generation;
  end if;
  insert into public.creator_revenue_cumulative_records(creator_profile_id, creator_entity_id, platform, platform_uid, cumulative_amount, previous_cumulative_amount, calculated_period_amount, data_date, week_start_date, entered_by_employee_id, source, entry_kind, related_weekly_revenue_record_id, idempotency_key, note)
  values(c.id, c.creator_entity_id, c.platform, c.platform_user_id, p_cumulative_amount, s.latest_cumulative_amount, v_period_amount, p_data_date, v_week_start, v_employee_id, p_source, 'calculation', v_weekly.id, p_idempotency_key, nullif(btrim(coalesce(p_note,'')),'')) returning * into v_raw;
  update public.creator_revenue_cumulative_state set latest_cumulative_amount = p_cumulative_amount, latest_raw_record_id = v_raw.id, updated_at = now() where creator_profile_id = c.id;
  return jsonb_build_object('idempotent', false, 'entry_kind', 'calculation', 'weekly_record', to_jsonb(v_weekly), 'previous_cumulative_amount', s.latest_cumulative_amount, 'calculated_period_amount', v_period_amount);
end;
$$;

create or replace function public.reset_creator_cumulative_revenue_baseline(
  p_creator_profile_id uuid, p_new_baseline_amount numeric, p_data_date date, p_reason text, p_idempotency_key uuid
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare c public.creator_profiles; s public.creator_revenue_cumulative_state; r public.creator_revenue_cumulative_records; v_employee_id uuid := public.current_user_employee_id(); v_reason text := nullif(btrim(coalesce(p_reason,'')), '');
begin
  if auth.uid() is null or not public.current_user_is_super_admin() then raise exception 'Only Super Admin can reset a cumulative revenue baseline.'; end if;
  if p_new_baseline_amount is null or p_new_baseline_amount < 0 or p_data_date is null or p_idempotency_key is null or v_reason is null then raise exception 'Reset requires a non-negative baseline, data date, idempotency key, and reason.'; end if;
  select * into c from public.creator_profiles where id = p_creator_profile_id;
  if c.id is null then raise exception 'Creator profile not found.'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_creator_profile_id::text, 0));
  select * into r from public.creator_revenue_cumulative_records where creator_profile_id = c.id and idempotency_key = p_idempotency_key;
  if r.id is not null then return jsonb_build_object('idempotent', true, 'entry_kind', r.entry_kind); end if;
  select * into s from public.creator_revenue_cumulative_state where creator_profile_id = c.id for update;
  if s.creator_profile_id is null then insert into public.creator_revenue_cumulative_state(creator_profile_id) values(c.id) returning * into s; end if;
  if p_data_date < (select raw.data_date from public.creator_revenue_cumulative_records raw where raw.id = s.latest_raw_record_id) then
    raise exception 'Reset data date cannot be earlier than the latest cumulative observation.';
  end if;
  update public.creator_revenue_cumulative_period_state set is_active = false, updated_at = now() where creator_profile_id = c.id and is_active;
  insert into public.creator_revenue_cumulative_records(creator_profile_id, creator_entity_id, platform, platform_uid, cumulative_amount, previous_cumulative_amount, data_date, week_start_date, entered_by_employee_id, source, entry_kind, idempotency_key, note)
  values(c.id, c.creator_entity_id, c.platform, c.platform_user_id, p_new_baseline_amount, s.latest_cumulative_amount, p_data_date, public.creator_weekly_revenue_period_start(p_data_date), v_employee_id, 'manual', 'reset', p_idempotency_key, v_reason) returning * into r;
  update public.creator_revenue_cumulative_state set latest_cumulative_amount = p_new_baseline_amount, latest_raw_record_id = r.id, chain_active = true, chain_generation = chain_generation + 1, updated_at = now() where creator_profile_id = c.id;
  return jsonb_build_object('idempotent', false, 'entry_kind', 'reset');
end;
$$;

revoke all on function public.assert_creator_cumulative_revenue_access(public.creator_profiles, boolean) from public, anon, authenticated;
revoke all on function public.get_creator_cumulative_revenue_context(uuid, date) from public, anon;
revoke all on function public.submit_creator_cumulative_revenue(uuid, numeric, date, uuid, text, text) from public, anon;
revoke all on function public.reset_creator_cumulative_revenue_baseline(uuid, numeric, date, text, uuid) from public, anon;
grant execute on function public.get_creator_cumulative_revenue_context(uuid, date) to authenticated;
grant execute on function public.submit_creator_cumulative_revenue(uuid, numeric, date, uuid, text, text) to authenticated;
grant execute on function public.reset_creator_cumulative_revenue_baseline(uuid, numeric, date, text, uuid) to authenticated;

commit;
