-- Standalone hotfix for the already deployed 001 Phase 1 RPCs.
-- This migration must run before 002/003 and therefore references no future RPC.

create or replace function public.create_designer_request(p_creator_profile_id uuid,p_work_mode public.designer_work_mode,p_request_type public.design_request_type,p_event_start_at timestamptz default null,p_event_end_at timestamptz default null,p_design_content text default null,p_style text default null,p_color text default null,p_specification text default null,p_special_content text default null,p_reference_material_status text default 'not_required',p_live_room text default null) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare c public.creator_profiles; rid uuid; eid uuid; st public.designer_stage_type; begin if auth.uid() is null then raise exception 'Authentication required'; end if; if not public.current_user_has_permission('agent-design-requests','use') then raise exception 'Permission denied.'; end if; select * into c from public.creator_profiles where id=p_creator_profile_id and status='active'; if c.id is null or not public.current_user_can_access_region(c.region_id) then raise exception 'Creator access denied.'; end if; if p_reference_material_status not in ('not_required','provided') then raise exception 'Invalid reference material status.'; end if; select id into eid from public.employees where profile_id=auth.uid() and deleted_at is null limit 1; insert into public.designer_requests(agent_profile_id,agent_employee_id,creator_profile_id,creator_entity_id,region_id,work_mode,request_type,platform,platform_user_id,creator_name,platform_account,event_start_at,event_end_at,design_content,style,color,specification,special_content,reference_material_status,live_room) values(auth.uid(),eid,c.id,c.creator_entity_id,c.region_id,p_work_mode,p_request_type,c.platform,c.platform_user_id,c.creator_name,c.platform_account,p_event_start_at,p_event_end_at,p_design_content,p_style,p_color,p_specification,p_special_content,p_reference_material_status,p_live_room) returning id into rid; st:=case when p_work_mode='setup_only' then 'setup' else 'design' end; insert into public.designer_request_stages(request_id,stage_type) values(rid,st); if p_work_mode='design_production' then insert into public.designer_request_stages(request_id,stage_type,status) values(rid,'production','scheduled'); end if; return rid; end $$;

create or replace function public.claim_designer_request_stage(p_stage_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare s public.designer_request_stages; eid uuid; begin if auth.uid() is null then raise exception 'Authentication required'; end if; select * into s from public.designer_request_stages where id=p_stage_id for update; if s.status<>'unclaimed' or not public.current_user_has_permission('designer-intake','use') or not public.can_access_designer_request(s.request_id) then raise exception 'Stage unavailable.'; end if; select id into eid from public.employees where profile_id=auth.uid() and deleted_at is null limit 1; update public.designer_request_stages set status=case when s.stage_type='setup' then 'scheduled' else 'in_progress' end,assignee_profile_id=auth.uid(),assignee_employee_id=eid,accepted_at=now() where id=s.id; end $$;

create or replace function public.advance_designer_request_stage(p_stage_id uuid,p_action text) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare s public.designer_request_stages; begin if auth.uid() is null then raise exception 'Authentication required'; end if; select * into s from public.designer_request_stages where id=p_stage_id for update; if s.assignee_profile_id<>auth.uid() or s.stage_type<>'setup' then raise exception 'Permission denied.'; end if; if p_action='arrange' and s.status='scheduled' then update public.designer_request_stages set status='arranged' where id=s.id; elsif p_action='start' and s.status='arranged' then update public.designer_request_stages set status='in_progress' where id=s.id; else raise exception 'Invalid transition.'; end if; end $$;

create or replace function public.submit_designer_request_stage(p_stage_id uuid,p_feedback text default null) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare s public.designer_request_stages; begin if auth.uid() is null then raise exception 'Authentication required'; end if; select * into s from public.designer_request_stages where id=p_stage_id for update; if s.assignee_profile_id<>auth.uid() or s.status not in ('in_progress','revision') then raise exception 'Invalid submission.'; end if; update public.designer_request_stages set status='awaiting_agent_confirmation',submitted_at=now(),feedback=coalesce(nullif(btrim(p_feedback),''),feedback) where id=s.id; end $$;

create or replace function public.confirm_designer_request_stage(p_stage_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare s public.designer_request_stages; r public.designer_requests; eid uuid; begin if auth.uid() is null then raise exception 'Authentication required'; end if; select * into s from public.designer_request_stages where id=p_stage_id for update; select * into r from public.designer_requests where id=s.request_id; if r.agent_profile_id<>auth.uid() or s.status<>'awaiting_agent_confirmation' then raise exception 'Confirmation denied.'; end if; select id into eid from public.employees where profile_id=auth.uid() and deleted_at is null limit 1; update public.designer_request_stages set status='completed',confirmed_at=now(),confirmed_by_profile_id=auth.uid(),confirmed_by_employee_id=eid where id=s.id; if s.stage_type='design' and r.work_mode='design_production' then update public.designer_request_stages set status='unclaimed' where request_id=r.id and stage_type='production' and status='scheduled'; else update public.designer_requests set status='completed',completed_at=now() where id=r.id; end if; end $$;

create or replace function public.return_designer_request_stage(p_stage_id uuid,p_feedback text) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare s public.designer_request_stages; r public.designer_requests; begin if auth.uid() is null then raise exception 'Authentication required'; end if; if nullif(btrim(p_feedback),'') is null then raise exception 'Feedback is required.'; end if; select * into s from public.designer_request_stages where id=p_stage_id for update; select * into r from public.designer_requests where id=s.request_id; if r.agent_profile_id<>auth.uid() or s.status<>'awaiting_agent_confirmation' then raise exception 'Return denied.'; end if; update public.designer_request_stages set status='revision',feedback=btrim(p_feedback),feedback_count=feedback_count+1 where id=s.id; end $$;

revoke all on function public.can_access_designer_request(uuid) from public, anon;
grant execute on function public.can_access_designer_request(uuid) to authenticated;
revoke all on function public.list_designer_request_creators() from public, anon;
grant execute on function public.list_designer_request_creators() to authenticated;
revoke all on function public.create_designer_request(uuid, public.designer_work_mode, public.design_request_type, timestamptz, timestamptz, text, text, text, text, text, text, text) from public, anon;
grant execute on function public.create_designer_request(uuid, public.designer_work_mode, public.design_request_type, timestamptz, timestamptz, text, text, text, text, text, text, text) to authenticated;
revoke all on function public.claim_designer_request_stage(uuid) from public, anon;
grant execute on function public.claim_designer_request_stage(uuid) to authenticated;
revoke all on function public.advance_designer_request_stage(uuid, text) from public, anon;
grant execute on function public.advance_designer_request_stage(uuid, text) to authenticated;
revoke all on function public.submit_designer_request_stage(uuid, text) from public, anon;
grant execute on function public.submit_designer_request_stage(uuid, text) to authenticated;
revoke all on function public.confirm_designer_request_stage(uuid) from public, anon;
grant execute on function public.confirm_designer_request_stage(uuid) to authenticated;
revoke all on function public.return_designer_request_stage(uuid, text) from public, anon;
grant execute on function public.return_designer_request_stage(uuid, text) to authenticated;
